# Generated by Django 3.0.5 on 2020-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='approved',
            field=models.DateTimeField(null=True),
        ),
    ]
